from pathlib import Path
p=Path('app/src/main/java/com/automicosta/app/ui/AutoMiCostaApp.kt')
s=p.read_text()
s=s.replace('var showMaintenance by remember { mutableStateOf(false) }','var showMaintenance by remember { mutableStateOf(false) }\n    var maintenanceEditor by remember { mutableStateOf<MaintenanceEntity?>(null) }')
s=s.replace('tab == Tab.MANUTENZIONE -> MaintenanceList(maintenance) { showKiaHistoryImport = true }','tab == Tab.MANUTENZIONE -> MaintenanceList(maintenance, { showKiaHistoryImport = true }) { maintenanceEditor = it }')
s=s.replace('if (showMaintenance && selected != null) AddMaintenanceDialog(selected.id, { showMaintenance = false }) { vm.addMaintenance(it); showMaintenance = false }','if (showMaintenance && selected != null) MaintenanceEditorDialog(null, selected.id, { showMaintenance = false }) { vm.addMaintenance(it); showMaintenance = false }\n    maintenanceEditor?.let { item -> MaintenanceEditorDialog(item, item.vehicleId, { maintenanceEditor = null }) { vm.updateMaintenance(it); maintenanceEditor = null } }')
s=s.replace('private fun MaintenanceList(items: List<MaintenanceEntity>, onImportKiaHistory: () -> Unit) {','private fun MaintenanceList(items: List<MaintenanceEntity>, onImportKiaHistory: () -> Unit, onEdit: (MaintenanceEntity) -> Unit) {')
old='if (m.note.isNotBlank()) Text(m.note, style = MaterialTheme.typography.bodySmall) } } }'
new='if (m.note.isNotBlank()) Text(m.note, style = MaterialTheme.typography.bodySmall); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) { TextButton(onClick = { onEdit(m) }) { Text("Modifica") } } } } }'
s=s.replace(old,new,1)
s=s.replace('private fun AddMaintenanceDialog(vehicleId: Long, onDismiss: () -> Unit, onSave: (MaintenanceEntity) -> Unit) {\n    var component by remember { mutableStateOf("Tagliando completo") }; var workType by remember { mutableStateOf("Sostituzione") }; var date by remember { mutableStateOf(today()) }; var cost by remember { mutableStateOf("") }; var km by remember { mutableStateOf("") }; var workshop by remember { mutableStateOf("") }; var partBrand by remember { mutableStateOf("") }; var partCode by remember { mutableStateOf("") }; var nextDate by remember { mutableStateOf("") }; var nextKm by remember { mutableStateOf("") }; var note by remember { mutableStateOf("") }; var expanded by remember { mutableStateOf(false) }','private fun MaintenanceEditorDialog(existing: MaintenanceEntity?, vehicleId: Long, onDismiss: () -> Unit, onSave: (MaintenanceEntity) -> Unit) {\n    var component by remember(existing) { mutableStateOf(existing?.component ?: "Tagliando completo") }; var workType by remember(existing) { mutableStateOf(existing?.workType ?: "Sostituzione") }; var date by remember(existing) { mutableStateOf(existing?.let { formatDate(it.dateEpochDay) } ?: today()) }; var cost by remember(existing) { mutableStateOf(existing?.cost?.toString().orEmpty()) }; var km by remember(existing) { mutableStateOf(existing?.odometerKm?.toString().orEmpty()) }; var workshop by remember(existing) { mutableStateOf(existing?.workshop.orEmpty()) }; var partBrand by remember(existing) { mutableStateOf(existing?.partBrand.orEmpty()) }; var partCode by remember(existing) { mutableStateOf(existing?.partCode.orEmpty()) }; var nextDate by remember(existing) { mutableStateOf(existing?.nextDueEpochDay?.let(::formatDate).orEmpty()) }; var nextKm by remember(existing) { mutableStateOf(existing?.nextDueKm?.toString().orEmpty()) }; var note by remember(existing) { mutableStateOf(existing?.note.orEmpty()) }; var expanded by remember { mutableStateOf(false) }')
s=s.replace('Text("Registra manutenzione", style = MaterialTheme.typography.headlineSmall','Text(if (existing == null) "Registra manutenzione" else "Modifica manutenzione", style = MaterialTheme.typography.headlineSmall',1)
s=s.replace('onSave(MaintenanceEntity(vehicleId = vehicleId, dateEpochDay = parseDate(date), component = component','onSave(MaintenanceEntity(id = existing?.id ?: 0, vehicleId = vehicleId, dateEpochDay = parseDate(date), component = component',1)
s=s.replace('}) { Text("Registra") } } } } }','}) { Text(if (existing == null) "Registra" else "Salva modifiche") } } } } }',1)
p.write_text(s)
